#' @name generate_command_spec
#'
#' @return A data frame of sub-commands with name, description, functions
#'     invoked and type
generate_command_spec <- function() {
    command_spec <- data.frame(
        name = c(
            'preprocess',
            'reduceDim',
            'partition',
            'learnGraph',
            'orderCells',
            'diffExp',
            'plotCells'
        ),
        description = c(
            'Normalisation, scaling, initial dimension reduction.',
            'Reduce dimensionality by UMAP.',
            'Partition cells into groups.',
            'Learn trajectories.',
            'Adjust the start of pseudo-time',
            'Identify genes with varing expression along trajectories.',
            'Visualise trajectories.'
        ),
        functions = c(
            'preprocessCDS',
            'reduceDimension',
            'partitionCells',
            'learnGraph',
            'orderCells,get_root_principal_nodes',
            'principalGraphTest',
            'plot_cell_trajectory'
        ),
        type = c('io', 'io', 'io', 'io', 'io', 'it', 'ip'),
        stringsAsFactors = FALSE
    )
    rownames(command_spec) <- command_spec$name
    command_spec
}

#' @name generate_command_usage
#' 
#' @param command_spec sub-command specification table generated by
#'     generate_command_spec()
#' @return Formatted usage text for the master command
generate_command_usage <- function(command_spec) {
    usage <- paste(
        'Usage: monocle3 [-h] <command> ...',
        '',
        'Commands:',
        paste(
            sprintf('  %-17s %-60s', command_spec$name, command_spec$description),
            collapse = '\n'
        ),
        '',
        'Options:',
        sprintf('  %-17s %-60s', '-h, --help', 'Show this help message and exit'),
        sep = '\n'
    )
}

#' Prepend function option names with function name, add options of common
#' functions according to command type
prepare_option_spec <- function(cmd_spec) {
    cmd_functions <- unlist(strsplit(cmd_spec$functions, ','))
    fn_options <- function_options(cmd_functions)
    for (i in seq_along(fn_options)) {
        fn_name <- cmd_functions[i]
        for (j in seq_along(fn_options[[i]])) {
            dest <- fn_options[[i]][[j]]@dest
            fn_options[[i]][[j]]@dest <- paste(fn_name, dest, sep='___')
        }
    }
    option_spec <- do.call('c', fn_options)
    if (grepl('p', cmd_spec$type)) option_spec <- c(output_plot_options(), option_spec)
    if (grepl('t', cmd_spec$type)) option_spec <- c(output_table_options(), option_spec)
    if (grepl('o', cmd_spec$type)) option_spec <- c(output_obj_options(), option_spec)
    if (grepl('i', cmd_spec$type)) option_spec <- c(input_options(), option_spec)
    option_spec <- c(option_spec, common_options())
}

#' Remove function name prefix from parsed option names, aggregate options from
#' the same function into separate lists
prepare_parsed_options <- function(opts, cmd_spec) {
    cmd_functions <- unlist(strsplit(cmd_spec$functions, ','))
    new_opts <- list()
    for (fn_name in cmd_functions) {
        fn_prfx <- paste0('^', fn_name, '___')
        k <- grep(fn_prfx, names(opts))
        names(opts)[k] <- sub(fn_prfx, '', names(opts)[k])
        new_opts[[paste0(fn_name, '_options')]] <- opts[k]
        opts[k] <- NULL
    }
    opts$help <- NULL
    c(opts, new_opts)
}

#' @name monocle_preprocess
#'
#' @importFrom BiocGeneric estimateSizeFactors estimateDispersions
#' @importFrom monocle preprocessCDS
monocle_preprocess <- function(
    input_object,
    output_object,
    input_object_format = 'cds3',
    output_object_format = 'cds3',
    introspective = FALSE,
    verbose = FALSE,
    preprocessCDS_options = list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    cds <- estimateSizeFactors(cds)
    cds <- estimateDispersions(cds)

    cds <- do.call(
        'preprocessCDS',
        c(list(cds, verbose=verbose), preprocessCDS_options)
    )

    monocle_write_obj(cds, output_object, output_object_format, introspective)
}

#' @name monocle_reduceDim
#'
#' @importFrom monocle reduceDimension
monocle_reduceDim <- function(
    input_object,
    output_object,
    input_object_format = 'cds3',
    output_object_format = 'cds3',
    introspective = FALSE,
    verbose = FALSE,
    reduceDimension_options = list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    cds <- do.call(
        'reduceDimension',
        c(list(cds, verbose=verbose), reduceDimension_options)
    )

    monocle_write_obj(cds, output_object, output_object_format, introspective)
}

#' @name monocle_partition
#'
#' @importFrom monocle partitionCells
monocle_partition <- function(
    input_object,
    output_object,
    input_object_format = 'cds3',
    output_object_format = 'cds3',
    introspective = FALSE,
    verbose = FALSE,
    partitionCells_options = list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    cds <- do.call(
        'partitionCells',
        c(list(cds, verbose=verbose), partitionCells_options)
    )

    monocle_write_obj(cds, output_object, output_object_format, introspective)
}

#' @name monocle_learnGraph
#'
#' @importFrom monocle learnGraph
monocle_learnGraph <- function(
    input_object,
    output_object,
    input_object_format = 'cds3',
    output_object_format = 'cds3',
    introspective = FALSE,
    verbose = FALSE,
    learnGraph_options=list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    cds <- do.call(
        'learnGraph',
        c(list(cds, verbose=verbose), learnGraph_options)
    )

    monocle_write_obj(cds, output_object, output_object_format, introspective)
}

#' @name monocle_orderCells
#'
#' @importFrom monocle orderCells
monocle_orderCells <- function(
    input_object,
    output_object,
    input_object_format = 'cds3',
    output_object_format = 'cds3',
    introspective = FALSE,
    verbose = FALSE,
    get_root_principal_nodes_options=list(),
    orderCells_options=list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    if (is.null(orderCells_options$root_pr_nodes) &&
        is.null(orderCells_options$root_cells)) {
        orderCells_options$root_pr_nodes <- do.call(
            'get_root_principal_nodes',
            c(list(cds), get_root_principal_nodes_options)
        )
    }

    cds <- do.call(
        'orderCells',
        c(list(cds, verbose=verbose), orderCells_options)
    )

    monocle_write_obj(cds, output_object, output_object_format, introspective)
}

#' @name monocle_diffExp
#'
#' @importFrom monocle principalGraphTest
monocle_diffExp <- function(
    input_object,
    output_table,
    input_object_format = 'cds3',
    output_table_format = 'tsv',
    introspective = FALSE,
    verbose = FALSE,
    principalGraphTest_options=list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    cds <- do.call(
        'principalGraphTest',
        c(list(cds, verbose=verbose), principalGraphTest_options)
    )

    monocle_write_table(cds, output_table, output_table_format, introspective)
}

#' @name monocle_plotCells
#'
#' @importFrom monocle plot_cell_trajectory
monocle_plotCells <- function(
    input_object,
    output_plot,
    input_object_format = 'cds3',
    output_plot_format = 'png',
    verbose = FALSE,
    plot_cell_trajectory_options=list()
) {
    cds <- monocle_read_obj(input_object, input_object_format)

    p <- do.call(
        'plot_cell_trajectory',
        c(list(cds, verbose=verbose), plot_cell_trajectory_options)
    )

    monocle_write_plot(p, output_plot, output_plot_format)
}
